#!/usr/bin/env python3
"""
DRAM Timing Visualizer & Verification Tool
Architecture-grade post-processing for C++ Simulation Traces.
"""
import sys
import json
import csv
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

class DeepVisualizer:
    def __init__(self, trace_file):
        self.trace_file = trace_file
        self.events = []
        self.power_profile = []
        self.max_cycle = 0

        # Physical Constants (Datasheet IDD values in mA - DDR4 approx)
        self.IDD = {
            'ACT': 45.0,  'PRE': 20.0,
            'RD':  180.0, 'WR':  165.0,
            'REF': 240.0, 'IDLE': 10.0,
            'ACTIVATE': 45.0, 'PRECHARGE': 20.0, # Handle full names
            'READ': 180.0, 'WRITE': 165.0,
            'REFRESH': 240.0
        }

    def parse_csv(self):
        """
        Parses the structured CSV generated by the C++ Simulator.
        Format: Cycle,Command,Bank,Row
        """
        print(f"Loading trace: {self.trace_file} (stream-aggregating)...")

        # Streaming aggregation parameters
        bin_size = 100  # cycles per power bin (tweakable)
        power_bins = {}  # bin_index -> [sum_ma, count]

        def cmd_to_state(cmd):
            up = cmd.upper()
            if up.startswith('ACT'):
                return 'ACTIVE'
            if up.startswith('READ') or up.startswith('RD'):
                return 'READING'
            if up.startswith('WRITE') or up.startswith('WR'):
                return 'WRITING'
            if up.startswith('PRE'):
                return 'PRECHARGING'
            if up.startswith('REF'):
                return 'REFRESHING'
            return None

        try:
            with open(self.trace_file, 'r') as f:
                reader = csv.DictReader(f)
                if not reader.fieldnames:
                    print('Warning: CSV appears empty.')
                    return

                current_state = 'IDLE'
                cur_start = 0
                cur_label = ''
                max_cycle = 0

                for row in reader:
                    try:
                        cycle = int(row['Cycle'])
                        cmd = row['Command'].strip()
                        bank_row = row.get('Row', '0')
                    except (ValueError, KeyError):
                        continue

                    max_cycle = max(max_cycle, cycle)

                    # Bin power
                    p = self.IDD.get(cmd, self.IDD.get(cmd[:3].upper(), 10.0))
                    b = cycle // bin_size
                    s = power_bins.get(b)
                    if s is None:
                        power_bins[b] = [p, 1]
                    else:
                        s[0] += p
                        s[1] += 1

                    # Determine new state
                    new_state = cmd_to_state(cmd)
                    # If command doesn't map to a state, keep current_state
                    if new_state is None:
                        # still advance last_time but no state change
                        continue

                    # If state changes, close previous interval
                    if new_state != current_state:
                        # Only append intervals that have positive duration
                        if cycle > cur_start:
                            self.events.append({'State': current_state, 'Start': cur_start, 'End': cycle, 'Label': cur_label})
                        # start new interval
                        current_state = new_state
                        cur_start = cycle
                        cur_label = (f'Row {bank_row}' if new_state == 'ACTIVE' else '')
                    else:
                        # same state: optionally update label if activate
                        if new_state == 'ACTIVE':
                            cur_label = f'Row {bank_row}'

                # finalize last interval
                if max_cycle >= cur_start:
                    self.events.append({'State': current_state, 'Start': cur_start, 'End': max_cycle + 1, 'Label': cur_label})

                # convert power_bins into profile (sorted by bin start)
                bins = sorted(power_bins.items())
                self.power_profile = []
                for bin_idx, (sum_ma, cnt) in bins:
                    start = bin_idx * bin_size
                    end = start + bin_size
                    avg = sum_ma / cnt if cnt else 0.0
                    self.power_profile.append((start, avg))

                self.max_cycle = max_cycle

                # write Matlab-friendly summaries
                with open('summary_trace.csv', 'w', newline='') as out:
                    w = csv.writer(out)
                    w.writerow(['Start', 'End', 'State', 'Label'])
                    for e in self.events:
                        w.writerow([e['Start'], e['End'], e['State'], e['Label']])

                with open('power_bins.csv', 'w', newline='') as out:
                    w = csv.writer(out)
                    w.writerow(['BinStart', 'BinEnd', 'AvgCurrent_mA'])
                    for start, avg in self.power_profile:
                        w.writerow([start, start + bin_size, avg])

                print(f'Wrote summary_trace.csv ({len(self.events)} intervals) and power_bins.csv ({len(self.power_profile)} bins)')

        except FileNotFoundError:
            print(f"Error: Trace file '{self.trace_file}' not found.")
            sys.exit(1)

    def add_annotation(self, cycle, text):
        """Annotate the specific event ending at this cycle"""
        if self.events:
            self.events[-1]['Label'] = text

    def export_dramsim3(self, output_path="dram_trace.json"):
        """
        Generates a valid JSON trace compatible with memory system verification tools.
        """
        print(f"Exporting DRAMSim3-compatible trace to {output_path}...")
        
        # Creating the artifact structure
        trace_data = {
            "standard": "DDR4",
            "frequency_mhz": 1200,
            "trace": [
                {"cycle": e['Start'], "command": e['State'], "bank": 0} 
                for e in self.events if e['State'] not in ["IDLE"]
            ]
        }

        with open(output_path, 'w') as f:
            json.dump(trace_data, f, indent=4)

    def plot(self):
        if not self.events:
            print("No events found to plot.")
            return

        # Intelligent sampling for large datasets
        max_events_to_plot = 50
        if len(self.events) > max_events_to_plot:
            print(f"Large dataset ({len(self.events)} events), showing first {max_events_to_plot} events")
            # Take first N events for clearer view
            events_to_plot = [e for e in self.events if e['State'] != 'IDLE'][:max_events_to_plot]
        else:
            events_to_plot = self.events

        # Get actual time range of events being plotted
        start_cycle = events_to_plot[0]['Start']
        end_cycle = events_to_plot[-1]['End']
        time_span = end_cycle - start_cycle
        
        print(f"Plotting {len(events_to_plot)} events from cycle {start_cycle} to {end_cycle}")

        # ============== FIGURE 1: Bank State Timeline ==============
        fig1, ax1 = plt.subplots(figsize=(22, 8))
        
        # Industry Standard Colors
        colors = {
            'IDLE': '#e0e0e0',      'ACTIVE': '#4caf50',    # Green
            'READING': '#2196f3',   'WRITING': '#f44336',   # Blue / Red
            'REFRESHING': '#9c27b0','PRECHARGING': '#ff9800' # Purple / Orange
        }

        # Draw each state as a full-height bar
        for e in events_to_plot:
            c = colors.get(e['State'], '#cfd8dc')
            duration = e['End'] - e['Start']
            
            # Full height bars
            ax1.barh(y=0.5, width=duration, left=e['Start'], height=0.8,
                    color=c, edgecolor='black', linewidth=1.5, alpha=0.95)
            
            # Label bars that are wide enough
            bar_width_ratio = duration / time_span
            if bar_width_ratio > 0.02:
                text_x = e['Start'] + duration/2
                display_text = e['Label'] if e['Label'] else e['State'][:4]
                
                ax1.text(text_x, 0.5, display_text, 
                        ha='center', va='center', fontsize=11, 
                        color='white', fontweight='bold',
                        bbox=dict(boxstyle="round,pad=0.2", facecolor='black', alpha=0.7))

        # Set x-axis to fit events exactly
        ax1.set_xlim(start_cycle - time_span*0.02, end_cycle + time_span*0.02)
        ax1.set_ylim(0, 1)
        ax1.set_yticks([])
        
        # Legend
        patches = [mpatches.Patch(color=v, label=k) for k, v in colors.items()]
        ax1.legend(handles=patches, loc='upper right', ncol=6, 
                  fontsize=12, frameon=True, shadow=True)
        
        ax1.set_xlabel("Simulation Cycles", fontsize=14, fontweight='bold')
        ax1.set_ylabel("Bank State", fontsize=14, fontweight='bold')
        ax1.set_title(f"DRAM Bank State Timeline (Cycles {start_cycle:,} to {end_cycle:,})", 
                     fontsize=16, fontweight='bold', pad=15)
        ax1.grid(True, axis='x', linestyle=':', alpha=0.5)
        
        plt.tight_layout()
        plt.savefig("dram_bank_states.png", dpi=150, bbox_inches='tight', facecolor='white')
        print("Bank state timeline saved to dram_bank_states.png")

        # ============== FIGURE 2: Power Profile ==============
        fig2, ax2 = plt.subplots(figsize=(18, 6))
        
        x_vals, y_vals = zip(*self.power_profile) if self.power_profile else ([], [])
        if x_vals:
            ax2.step(x_vals, y_vals, where='post', color='#d32f2f', linewidth=2)
            ax2.fill_between(x_vals, y_vals, step='post', alpha=0.25, color='#d32f2f')
            
            ax2.axhline(y=50, color='green', linestyle='--', alpha=0.6, linewidth=1.5, label='Low Power')
            ax2.axhline(y=150, color='orange', linestyle='--', alpha=0.6, linewidth=1.5, label='High Power')
            ax2.axhline(y=200, color='red', linestyle='--', alpha=0.6, linewidth=1.5, label='Critical')

        ax2.set_ylabel("IDD Current (mA)", fontsize=14, fontweight='bold')
        ax2.set_xlabel("Simulation Cycles", fontsize=14, fontweight='bold')
        ax2.set_ylim(0, 300)
        ax2.grid(True, linestyle='--', alpha=0.5)
        ax2.set_title("Power Consumption Profile", fontsize=16, fontweight='bold')
        ax2.legend(loc='upper right', fontsize=11)
        
        plt.tight_layout()
        plt.savefig("dram_power_profile.png", dpi=150, bbox_inches='tight', facecolor='white')
        print("Power profile saved to dram_power_profile.png")
        
        plt.show()

if __name__ == "__main__":
    # Expects the CSV file generated by enable_tracing()
    infile = sys.argv[1] if len(sys.argv) > 1 else "trace_dramsim3.txt"
    
    viz = DeepVisualizer(infile)
    viz.parse_csv()
    viz.export_dramsim3()
    viz.plot()

